enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  babel-preset-react-app@10.0.x:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.16.0

yarnPath: .yarn/releases/yarn-3.2.1.cjs
